# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e36a5504041b01b7e441afc7367337cf4135992690a87361761de53fbc75603b602af1f79d5baa98ae5bf7a80eb0aaed7ef65950915b9bc2048f22e4e7b9b55

test:
  secret_key_base: 6626064b086524635b146973bfbb5d4112583c32d854e5fb78ff579a205900bca8ae91dcc0c9bb825bd2d40e9db0e6f89fa94c40488405be231577dcc5b1c9b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
